### ISSUE TITLE
Filter function

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#12]
## Value proposition

As a gardening enthusiast
I want to have filter options on the home page
In order to find plants that fulfill my wishes

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/7fae16c1-dd13-437c-88db-cf3f62038022)

## Acceptance criteria

- [ ] On the homepage there are 3 select inputs from which I can choose the filter options: Crop type (options:. herb, fruit, vegetable, other) , placement (options: bed, pot, bed or pot), growing conditions (options: sunny, partial shade)
- [ ] When I select one filter option, the Card List is filtered and only plants with the selected option are shown. Each other filter I select filters the filtered list.
- [ ] Once I've set a filter, there appears a reset button to reset the filter

## Tasks

- [ ] Create a function that uses the filter method, filters for the selected value and returns the filtered results as a new array of IDs, so that only the plants are shown for which the used filter is true
- [ ] Create select input fields
- [ ] Create a reset button that resets the select inputs so that the filter function is no longer applied and the complete list of plants is displayed again.
