### ISSUE TITLE
Display seed period on details page

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#13]
## Value proposition

As a gardening enthusiast
I want  to see the time period when i have to sow a particular plant
In order to plan my gardening year

## Description

**tbd**

## Acceptance criteria

- [ ] each plant receives a new data set sowingPeriod (maybe an array of months like ["April", "May", "June"] or a from-to date? tbd. )
- [ ] The new data is displayed on the plant details page
- [ ] The data record is displayed in a calendar format or a timeline in which the relevant time period is highlighted
- [ ] The sowingPeriod field is also available in the create plant/edit plant form (maybe in a dropdown menu of months of which the user can select one or several months / or a calender field. )

## Tasks

- [ ] Create a new data set and update the plants collection in the DB, so that every plant receives the new data
- [ ] Style a table with 12 columns that represents a calendar and render it on the plant details page or use a timeline component
- [ ] In the calendar/timeline, highlight the months that the sowingPeriod of the respective plant contains
- [ ] Add a new field to the CreatePlant and EditPlant forms
