### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#14]
## Value proposition

As a user
I want to be able login to the app with my GitHub account
in order to be able to create, edit and delete crops and to create my own garden (bookmark plants).

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/67c3a1a6-3b34-48a8-a84b-fb54e2c4fe23)

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/642fa257-9249-490b-b945-76d214263886)

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/fc90a86f-f1e7-4b29-96aa-ff94262944ff)

## Acceptance criteria

- [ ] The user should be able to login with a Github account
- [ ] If the user is not logged in, there is no possibility to create, edit or delete plants:
- [ ] For create the user get's an info that a login is necessary
- [ ] Edit & Delete are not shown an details page if not logged in
- [ ] There is a login icon on top of the page which directly links to the login page
- [ ] If the user is logged in, there is the possibility to create new plants and to edit or delete custom plants BUT not the default plants
- [ ] If the user is logged in, the login icon on top of the page turns into a logout icon.
- [ ] If the user clicks the logout icon, a model opens "Do you really want to log out?" providing two buttons - one to cancel the action and one to confirm the action. After the logout the user is pushed back to home

## Tasks

- [x] Check out the handout in the Capstone documents (see tasks) & understand how to implement the user login
- [x] Create a feature branch ```feature-user-login```
- [x] Follow the instructions on https://web-capstone-docs.neuefische.de/additional-libraries/nextauth to implement the user login
- [x] Create a login page which enables login with GitHub
- [x] Block the create page if the user is not logged in --> show an info, if the user tries to access the edit functionality and ask the user to login
- [x] Don't show the edit and delete functionality if the user it not logged in
- [x] Disable the edit and delete functionality for default plants, if the user is logged in
- [x] Implement an info on the "My Garden" page that the favourites are only saved  in local storage
- [x] Add a login icon on top of the page, linking to the login page
- [x] Turn the login icon into a logout icon once the user is logged in
- [x] If the user clicks the logout icon, open a modal to confirm or cancel the logout. Once confirmed, log the user out, redirect to the homepage and  show a toast message
