### ISSUE TITLE
Fix grid styling and header

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#15]
## Value proposition

As a developer
I want to refactor some components
In order to fix some styling issues 

## Description

- Issue: card has a fixed design and does not re-render depending on Viewport, this leads to the issue that on smaller devices, the grid exceeds the viewport and therefore the header seems displaced (see screenshot).
-  Solution:  fix the grid so the header issue is fixed. 

![Image](https://github.com/SabinePfanner/plants-app/assets/163883411/8e344147-c139-449f-a662-5900b010b1ed)

- Refactor the card component so that the card contains image, details, button which can be rendered individually (see also https://mui.com/material-ui/react-card/)

## Acceptance criteria

- [ ] Grid does not exceed viewport (header is placed correctly)
- [ ] Card component is refactored and correctly rendered in the `PlantDetails`and `CardList`

## Tasks

- [ ] Create a new design for the card
- [ ] Create a dynamic card component 
- [ ] Implement the new card component in `CardList`
- [ ] Implement the new card component in `PlantDetails`
- [ ] Challenge grid structure of `CardList`--> if we decide to keep the grid structure, make grid dynamic, otherwise refactor to flexbox
