### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#19]
## Value proposition

As a garden enthusiast
I want to upload an image when creating a new plant or editing a plant
In order to display how the plant looks like

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/163883411/6fb3143b-fab6-4a26-b545-04f2c3f23598)

## Acceptance criteria

- [ ] Users can upload an image when creating or editing a plant
- [ ] Cloudinary is set up for image storage

## Tasks

- [ ] Create new field for the image upload in the create/edit form and define where in the form it is placed (position in the wireframe is just an example)
- [ ] Set up cloudinary for uploading the images (see https://web-capstone-docs.neuefische.de/additional-libraries/cloudinary)
- [ ] Move the default images from public/images to cloudinary and adjust the URLs in the database OR decide to leave the default pictures locally (tbd)
- [ ] Save the images in a cloudinary collection, each image with a reference to the plant it belongs to
