### ISSUE TITLE
Overview of crop plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#2]
# Overview of Crop Plants

## Value Proposition

**As a** gardening enthusiast,

**I want to** see a list of crop plants,

**so that** I can browse through the collection to get inspiration for new crop plants.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/278ce1ee-df3b-4404-b254-f8677ff0eee5)

## Acceptance Criteria

- A header bar with a logo on top of the page
- A clear and concise list of all crop plants (fetched from MongoDB database) is displayed upon starting the App
- Each plant is display in a teaser - each teaser must include: 1.  preview image, 2. the crop plant name, 3. the cateogry, the crop plant is sorted to
- The list should be 2 crop plants p. row and vertically scrollable to accommodate a large number of plants.

## Tasks

- [ ] Create feature branch `feature/overview-of-plants`
- [ ] App level: Configure `SWR` config
- [ ] Create a basic dataset (array of objects) of crop plants in MongoDB, following this structures:

```
[
  {
    "_id": "eb8fb5fc-880", 
    "name": "Tomato", // type: string; value: user-defined
    "botanicalName": "Solanum lycopersicum", // type: string; value: user-defined
    "waterDemand": "High", // type: string; value:  'Low', 'Medium' or 'High'
    "nutrientDemand": "High", // type: string; value:  'Low', 'Medium' or 'High'
    "growingConditions": "Sunny", // type: string; value:  'Sunny', 'Partial shade'
    "placement": "Bed/Pot", // type: string; value:  'Bed', 'Pot' or 'Bed/Pot'
    "perennial": false, // type: boolean; value: true if perennial, false if annual
    "frostSensitive": true, // type: boolean; value: true if frost sensitive, false if not
    "cropType": "Vegetable", // type: string; value:  'Vegetable', 'Fruit', 'Herb' or 'Other'
    "image": "/images/tomato.png" // type: string; value: path to image
  }
]
```

- [ ] Create an API Connection to MongoDB 
- [ ] `GET` all `plants` from API endpoint `api/plants`
- [ ] Implement the error handling logic to display an error message if there's an issue loading the data from the database
- [ ] Create a component `card` and `card list`
- [ ] On homepage `(pages/index.js)` render the component `card list`
- [ ] Add the logo asset above the list on top of the homepage
