### ISSUE TITLE
Overall styling

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#20]
## Value proposition

As a developer
I want to add some global styling to my app
In order to achieve a better look and to make styling changes easier

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/109c13d3-86c2-4197-abb4-ab7c0fd15b77)

Color-schema:

--primary-light: #add0a5;
--primary-light-contrast: #423e3e;
--primary: #79af6e;
--primary-contrast: #1D0B07;
--primary-dark: #5c9651;
--primary-dark-contrast: #1D0B07;

--secondary: #e62600;
--secondary-contrast: #1D0B07;
--secondary-light-300: #ffa795;
--secondary-light-contrast: #1D0B07;
--secondary-light-200: #ffcbc1;

--accent: #f67b00;
--accent-contrast: #1D0B07;

--success-border: #5c9651;
--success-background: #add0a5;
--success-contrast: #1D0B07;

Font: Lato

## Acceptance criteria

- [ ] The font is Lato
- [ ] All components have a proper styling following common colours
- [ ] Per default, the main content should be centred on the page
- [ ] The cards within the card list behave equally on all devices
- [ ] The cards show an icon for the crop type
- [ ] Default data can be identified within the card list by an appropriate icon

## Tasks

- [ ] Add color variables to global styles and use them within the app
- [ ] Choose a font and implement it using next/fonts
- [ ] Align the content on every page to the center
- [ ] Check styling of card list and implement a solution to make it responsive
- [ ] Choose an icon to display the crop type on the card
- [ ] Implement an identifier on the card of default plants
- [ ] Place the card image within a proper image container to enable a smoother behaviour on all devices
