### ISSUE TITLE
Display more task periods on details page

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#21]
## Value proposition

As a gardening enthusiast
I want to see the time period when i can cultivate, plant, harvest and prune the crops from  a particular plant
In order to plan my gardening year

## Acceptance criteria

- [ ] After implementing the seed period on the details page (see https://github.com/users/SabinePfanner/projects/2/views/1?pane=issue&itemId=65503925) , the cultivate, plant, harvest and prune periods are implemented in the same way
- [ ] Each of the five task periods can be defined in the add plant / edit plant form.
- [ ] For each plant, (only) those periods defined for the respective plant are displayed on the plant's detail page via the custom timeline component. In addition, a color-coded overview is displayed for each period defined.

## Tasks
- [ ] Create a new data set for every new task and update the plants collection in the DB, so that every plant receives the new data
- [ ] For each new task period, add a timeline to define the period in the Create Plant/Edit Plant form
- [ ] On a plant's details page, render those periods that are defined for the respective plant.
