### ISSUE TITLE
Style header and footer

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#23]
## Value proposition

As a developer
I want to add some styling to the header and footer
In order to make my app look better 

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/163883411/b442886c-f0b0-4998-86d3-9ebefa790496)

## Acceptance criteria

- [ ] Header is overall smaller and only includes logo + app-title
- [ ] Current back button on the crop detail-page is replaced by a proper icon
- [ ] Navigation items are replaced by icons and are highlighted when ```active```
- [ ] Navigation bar is  overall smaller and does not overlay other page content

## Tasks

- [x] Re-factor the header component by adaption its size and the content
- [x] Add new icons for back, home and bookmark-page to the svg component
- [x] Replace the back button with the new icon and adjust the styling appropriately
- [x] Replace the navigation links via the new icons
- [x] Add a styling to the navigation icons which differentiates between inactive and active status
- [x] Re-factor the navigation component so that it does not overlay other functionalities within the app
