### ISSUE TITLE
Add filter for own plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#27]
## Value proposition

As a user
I want to be able to filter for my own plants
In order to just see the plants I've created myself

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/46643061-3811-47cf-81d0-028bdaf0839a)

## Acceptance criteria

- [ ] Besides the filter options `Crop Type`, `Placement` and `Growing Conditions` I can filter after the `owner` of the plants - either "default" or "myself"

## Tasks

- [ ] Create a feature branch
- [ ] Implement a  new filter  within the filter bar to filter for key values from ```owner:```
- [ ] Implement ```Default Crops``` and ```My Crops```as filter options
- [ ] For "My Crops" the list should include all crops of the user, so crops which are not ```default```
