### ISSUE TITLE
Sorting of plant list

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#28]
## Value proposition

As a user
I want the newest plants to appear at the top
so I can easily see my most recently created plants first.

## Description

/

## Acceptance criteria

- [ ] Plants list is sorted after initial creation date, newest first and default data last
- [ ] The sorting persists regardless the filter

## Tasks

- [ ] Create a feature-branch
- [ ] Add a new key to the database object, saving the creation date
- [ ] Implement a default sorting for the component ```CardList.js``` - after creation date, newest first
- [ ] On editing a plant, the initial creation date is not updated
- [ ] Make sure, that the sorting and the filter work together
- [ ] This might help: https://mongoosejs.com/docs/timestamps.html
