### ISSUE TITLE
Crop images

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#29]
## Value proposition

As a  garden enthusiast
I want to upload an image of my plant in portrait format or landscape format
In order to have a visual impression how the plant looks like

## Acceptance criteria

- [ ] If an image in any width/height ratio is uploaded in the edit/create plant form, it is displayed correctly on the card list and on the plant details page and is not distorted, but still fills the complete image area of the card without any white space

## Tasks

- [ ] Check https://nextjs.org/docs/pages/api-reference/components/image if this contains a solution for our needs and if yes, implement it
- [ ] Otherwise look for another package that could help
- [ ] Give the default image a heigt and width to solve the console errors
- [ ] Exchange the white placeholder image for another placeholder image

**Comment by SabinePfanner** [comment]
![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/6180d487-09ca-443e-8300-9661c2086d02)
