### ISSUE TITLE
Detail page plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#3]
# Plants detail page

## Value Proposition

**As a** gardening enthusiast,

**I want to** access detailed information about each crop plant in the overview,

**so that** I can get a better understanding of the plant's characteristics as well as its needs and care requirements.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/5ef47c64-1423-4601-b044-2fc83d85a7e3)

## Acceptance Criteria

- Selecting a plant from the `plants` opens a detailed view containing:
   - an (placeholder) image of the plant,
  - its name,
  - its botanical name,
  - the plant type,
  - whether the plant is annual or perennial
  - its placement 
  - its growing condition
  - its water demand,
  - its nutrient demand, and
  - whether it is frost sensitive
  

- The detailed view includes a "Back" link or button, allowing users to easily navigate back to the main list of plants.

## Tasks

- [ ] create feature branch `feature/plant-details`
- [ ] create a dynamic route for the details page under  pages/[id].js
- [ ] on this page, render the `Plant` component and within it a `Details` component: the `Plant` component conditionally only renders the image depending on the `details` prop; the detail information listed above is rendered below by the `Details` component.
- [ ] create an API endpoint under pages/api/[id].js
- [ ] on this page, define a handler function. In this function, define the case for the `GET` method: get (`findById`) and return the respective plant from the database. Implement proper error handling.
