### ISSUE TITLE
Move My-Garden to Login area

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#33]
## Value proposition

As a  plant enthusiast
I want to access my favorite plants in the login area
In order to see my favorite plants on all my devices

## Acceptance criteria

- [ ] A logged in user can see his favourite plants in "My Garden" regardless the device he is logged in
- [ ] A not logged in user can only see his favourite plants on his device/browser

## Tasks

- [ ] Create a second collection for the favourites in MongoDB that refers to the owner and contains  a list of ids of the owner's favorites
- [ ] For logged in users, save the ids of the plants in "MyGarden" in this collection but keep also the local storage
- [ ] Update the collection when a logged in user adds or removes a plant to/from his favorites
