### ISSUE TITLE
Notifications about tasks

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#34]
## Value proposition

As a garden enthusiast
I want to receive notifications to water my plants
In order to keep them alive

## Acceptance criteria

- [ ] For plants in my garden with high water need, I am reminded to water the plant every 2 days
- [ ] For plants in my garden with medium water need, I am reminded to water the plant every 5 days
- [ ] For plants in my garden with low water need, I am reminded to water the plant every 9 days
- [ ] To discuss: Only for logged in users, when favourites are saved in MongoDB?

## Tasks

- [ ] Create a notification snackbar for the watering reminder
- [ ] Add a component that counts the time
- [ ] For every plant that is in the user's "My garden" page (=favourites collection in the db), show the reminder snackbar according to the defined schedule
