### ISSUE TITLE
Style details page

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#35]
## Value proposition

As a user
I want to see all plant details in an easily understandable and appealing visualisation
In order to easily grab the plants characteristics and to dos.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/d324afb0-852f-4f25-82d8-3ef053623a43)

## Acceptance criteria

-[ ] The plant details page should have an appealing design (cf. wireframe)
-[ ] As a user I can easily see all the plants details, visualised via appropriate icons

## Tasks

- [ ] Create a feature-branch
- [ ] Choose appropriate icons for the different characteristics
- [ ] Display the characteristics as designed in the wireframe
- [ ] Adapt the styling of the calendar by using global styling colors
- [ ] Disable the edit and delete button with a lock for default data
- [ ] Implement media queries to guarantee, that the plant image is always display in a good quality
