### ISSUE TITLE
Add more images on details page

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#43]
## Value proposition

As a garden enthusiast
I want to add more images to my plants
In order to keep a diary how my plants grow

## Acceptance criteria

- [ ] On the plant details page of plants I created, I can see a multiple image upload where I can add more pictures
- [ ] I can also delete these pictures
- [ ] The uploaded pictures are displayed in a carousel

## Tasks

- [ ] Create feature branch
- [ ] Import carousel component from library
- [ ] copy the image upload from the form component and adjust it, so it allows multiple images and adds the newly uploaded images to the existing ones (does not overwrite them)
- [ ] Style the carousel according to the rest of the details page
- [ ] Hide the image upload for default plants
