### ISSUE TITLE
Edit Readme

### ISSUE THREAD

**Issue by evabergold** [SabinePfanner/plants-app#45]
## Value proposition

As a fellow developer
I want to see what the app is about
In order to get a first overview

## Acceptance criteria

- [ ] Project has a readme with app description, tech stack, team members and screenshot

## Tasks

- [ ] Edit the readme file accordingly
- [ ] Make some minor styling changes
