### ISSUE TITLE
My garden page

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#5]
# My Garden Page

## Value Proposition

**As a** gardening enthusiast,

**I want to** have a dedicated space for my crop plants,

**so that** I can easily manage and view plants that I personally own.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/d776151c-9392-4ab9-acb7-c9dd3d717e2a)

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/15dfc3d9-a224-4860-a085-325979b204b7)

## Acceptance Criteria

- There is a navigation bar that allows the user to switch between the homepage and the `My Garden` page
- The navigation bar is fixed to the bottom of the viewport
- Each listed plant includes an easily accessible option to add to a section or page called "My Garden "
- The "Add to My Garden" option is intuitive to find in the top right corner of the plant card, perhaps represented by an icon  (visible on the homepage, the details page and the "My Garden" page)
- Selected plants can be added and removed from the "My Garden List" using the icon.
- The plants selected as "My Garden" are visually highlighted (e.g., icon color)

On the "My Garden" page: 
- This page displays all plants selected by the user.
- Users can view, access, and manage their saved plants in this section.
- When a user clicks on a plant on the "My Garden" page, they are directed to the plant detail page.
- If the user hasn't selected any plants yet, a text is displayed on the "My Garden" page, indicating there are no plants in the "My Garden" list and encouraging the user to add some. 

## Tasks

- [x] Create feature branch `feature/my-plants`
- [x] Create a `Navigation` component
- [x] add a `Link` component 
- [x]  Create a `Footer` component to position the navigation
- [x] add the `Navigation` component
- [x] Render the `Footer` component in the _app.js
- [x] Create a state for the plant component 
- [x] Implement a function that adds or removes plant from `My Garden` when the bookmark icon is clicked 
- [x] create the page pages/my-garden.js
- [x] Reuse and filter the `PlantList`component to display the plants that were added to MyGarden
- [x] Display a message on the My Garden page if it's empty indicating there are no plants in the "My Garden" list and encouraging the user to add some.
