### ISSUE TITLE
Create plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#6]
# Create Plant Entries

## Value Proposition

**As a** gardening enthusiast,

**I want to** add my own plant entries to the app,

**so that** I can track their care in a personalized manner.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/119373f6-6e6f-47a0-9c9c-33d5d5765c53)

OPTIONAL DESIGN FOR CONFIRMATION MESSAGES

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/2d86ae06-ce9a-42ba-a303-ecc64ff725c9)

## Acceptance Criteria

- A new "add plant" button is visible in the lower right corner of the homepage and the "MyGarden" page.

- Users can add new plant entries, specifying

> -  the name,
> - the botanical name,
> - the water demand,
> - the nutrient demand,
> - the growing conditions,
> - the placement,
> - the information if a plant is perennial or not,
> - the information if a plant is frost sensitive or not,
> - the crop type

- All of the above fields are mandatory, with a character limit between 1 and 75.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Below the form there are two buttons: Dismiss and Submit:

1. When the user clicks on "Dismiss", the user is asked if he really wants to dismiss the changes, which he can confirm or cancel. (Optional: as an overlay, see wireframe "Optional"). By clicking "cancel", the user stays on the form. By clicking "Dismiss all changes", the entered form values are not saved and the user is directed back to the homepage.
2. When the user clicks "Submit", a new plant object is created and added to the database. The user is directed to the detail page of the plant. On top of the page, a timed success message is shown indicating the plant was successfully created. The new plant is also added is added to the top of the homepage

## Tasks

- [ ] Create feature branch `feature/create-plant-entries`
- [ ] Add the `create`route
- [ ] Create a form component/page that allows users to add new plants (see wireframe)
- [ ] Implement a function `handleSubmit` that adds a new plant to the database when the form is submitted
- [ ] Create a timed success message
- [ ] Handle the button logic for the dismiss button including the necessary states
- [ ] Add a "add new plant" button on the homepage and the "MyGarden" page which leads to the form page
