### ISSUE TITLE
Delete plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#7]
# Delete Plant Entries

## Value Proposition

**As a** plant owner,

**I want to** delete plant entries from my plant collection and the plant database,

**so that** I can keep my app updated with only the plants need.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/75c6635c-113c-429a-8acf-ea06db74512f)

OPTIONAL DESIGN FOR CONFIRMATION

![Image](https://github.com/SabinePfanner/plants-app/assets/164749128/5df6692c-881f-4ec7-9fff-0c48289143ac)

## Acceptance Criteria

- Each plant detail page includes an easily accessible "Delete" option.
- The "Delete" option is intuitive to find, represented by a trash can icon on the detail page.
- Clicking the "Delete" button triggers a confirmation dialog (check design options).
- The dialog includes options for both confirming the deletion and cancelling the action.
- Really delete button is in a different place than the delete button
- The cancellation option allows the user to back out of the deletion process if selected by mistake or changed mind.
- Upon deletion, the plant entry is immediately removed from the plants collection and the user is redirected to the overview page.

## Tasks

- [x] Create feature branch `feature/delete-plants`
- [x] Create a delete button displayed on the plant detail page
- [ ] Write a `handleDelete` function, handling the delete option by including a necessary state logic `idDeleteMode`
- [ ] API endpoint pages/api/[id].js: within the handler function, define the case for the `DELETE` method to delete the respective plant entry (`findByIdAndDelete`) from the data base. Implement proper error handling.
- [x] Display a confirmation button-set  to confirm or dismiss the deletion
- [x] Display a timed success message, once the plant is deleted
