### ISSUE TITLE
Edit plants

### ISSUE THREAD

**Issue by SabinePfanner** [SabinePfanner/plants-app#8]
# Edit Plant Entries

## Value Proposition

**As a** garden enthusiast,

**I want to** edit the details of my plant entries,

**so that** I can keep the information accurate and up to date.

## Description

![Image](https://github.com/SabinePfanner/plants-app/assets/163883411/1d95f40b-335a-4c74-a7b5-124c30744887)

## Acceptance Criteria

- Users can edit any detail of their plant entries

- The "Edit" option is intuitive to find, represented by a pencil icon in the lower right corner of the detail page of the plant
- Clicking "Edit" opens a form pre-filled with the plant's existing details for modification.
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or their changed mind.
- Submissions with empty required fields are blocked, with validation messages guiding completion.
- Changes are saved and immediately reflected in the app, a timed success message is displayed
- Users receive feedback on successful updates or errors in their entry form.

## Tasks

- [ ] Create feature branch `feature/edit-plants`
- [ ] Create the route `/edit/[id]`
- [ ] Re-use the form component for "create plants" and fill in the current values of the plant as default values
- [ ] Implement an `EditPlant` function that updates the edited values, including the necessary states
- [ ] Add a timed success message
- [ ] Handle the button logic for the dismiss button including the necessary states
- [ ] Add a pencil icon to the detail page, by clicking on the pencil icon you are directed to the "edit plant" form
- [ ] API endpoint pages/api/[id].js: within the handler function, define the case for the `PUT` method to update the respective plant entry (`findByIdAndUpdate`). Implement proper error handling.
